Proposing fix for Openssl error & string.h errors
*Several errors showed up while compiling the above code in my Kali (Linux Unknown 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux)  using gcc (gcc version 9.2.1 20191130 (Debian 9.2.1-21)

Managed to solve the above issues using the following approaches : (Hope this helps)
1. Required to install this SSL package to avoid Openssl errors : apt-get install libssl-ocaml-dev

2.Following errors show up while compilation in gcc if string.h is not included in the above code :

exploit3.c: In function ‘gethostbyname_’:
exploit3.c:205:4: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
  205 |    memset(&server, '\0', sizeof(struct sockaddr_in));
      |    ^~~~~~
exploit3.c:205:4: warning: incompatible implicit declaration of built-in function ‘memset’
exploit3.c:63:1: note: include ‘<string.h>’ or provide a declaration of ‘memset’
   62 |   #include <netdb.h>
  +++ |+#include <string.h>
   63 |   #include <sys/socket.h>
exploit3.c:206:4: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
  206 |    memcpy(&server.sin_addr, he->h_addr_list[0],  he->h_length);
      |    ^~~~~~
exploit3.c:206:4: warning: incompatible implicit declaration of built-in function ‘memcpy’
exploit3.c:206:4: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
exploit3.c: In function ‘main’:
exploit3.c:302:25: warning: implicit declaration of function ‘strlen’ [-Wimplicit-function-declaration]
  302 |         target = calloc(strlen(optarg)+1, sizeof(char));
      |                         ^~~~~~
exploit3.c:302:25: warning: incompatible implicit declaration of built-in function ‘strlen’
exploit3.c:302:25: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
exploit3.c:307:9: warning: incompatible implicit declaration of built-in function ‘memcpy’
  307 |         memcpy(target, optarg, strlen(optarg)+1);
      |         ^~~~~~
exploit3.c:307:9: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
exploit3.c:315:29: warning: incompatible implicit declaration of built-in function ‘strlen’
  315 |           protocol = calloc(strlen(optarg)+1, sizeof(char));
      |                             ^~~~~~
exploit3.c:315:29: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
exploit3.c:320:11: warning: incompatible implicit declaration of built-in function ‘memcpy’
  320 |           memcpy(protocol, optarg, strlen(optarg)+1);
      |           ^~~~~~
exploit3.c:320:11: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
exploit3.c:321:16: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
  321 |           if (!strcmp(protocol, "https"))
      |                ^~~~~~
exploit3.c:372:23: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
  372 |     interpreters[0] = strdup("/cgi-bin/php");
      |                       ^~~~~~
exploit3.c:372:23: warning: incompatible implicit declaration of built-in function ‘strdup’
exploit3.c:430:16: warning: incompatible implicit declaration of built-in function ‘strlen’
  430 |      tmpsize = strlen(phpstr) + strlen(reverseip) + strlen(reverseportstr) + 64;
      |                ^~~~~~
exploit3.c:430:16: note: include ‘<string.h>’ or provide a declaration of ‘strlen’